[profile.default]
via_ir = true
evm_version = "prague"
fs_permissions = [{ access = "read-write", path = "./" }]
optimizer = true
optimizer_runs = 1000
solc_version = "0.8.30"

[fuzz]
runs = 100
seed = '0x4444'